version: '3.5'

services:

  odoo:
    container_name: "odoo${ODOO_VERSION}"
    command: start
    environment:
      #- ADDONS_REPO=myrepo ${ODOO_VERSION} 
      - DISPLAY
      - FETCH_OCA_DEPENDENCIES=True
      - ODOO_ADMIN_PASSWD=STRONG_ODOO_MASTER_PASSWORD 
      - ODOO_DB_HOST=localhost
      - ODOO_DB_PASSWORD=STRONG_PG_ODOO_PASSWORD 
      - ODOO_DB_USER=odoo${ODOO_VERSION}
      - TARGET_UID=$UID
    #image: elicocorp/odoo:${ODOO_VERSION}
    image: odoo-pycharm:${ODOO_VERSION}
    network_mode: "host"
    ports:
      - "8069:8069"
      - "8072:8072"
      - "8169:8169"
      - "8172:8172"
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - ${ODOO_ROOT}/${ODOO_VERSION}/.idea:/opt/odoo/.idea
      - ${ODOO_ROOT}/${ODOO_VERSION}/addons:/opt/odoo/additional_addons
      - ${ODOO_ROOT}/${ODOO_VERSION}/etc:/opt/odoo/etc
      - ${ODOO_ROOT}/${ODOO_VERSION}/filestore:/opt/odoo/data/filestore
      - ${ODOO_ROOT}/${ODOO_VERSION}/letsencrypt:/opt/odoo/data/letsencrypt
      - ${ODOO_ROOT}/${ODOO_VERSION}/scripts:/opt/scripts
      - ${ODOO_ROOT}/${ODOO_VERSION}/sessions:/opt/odoo/data/sessions
      - ${ODOO_ROOT}/${ODOO_VERSION}/ssh:/opt/odoo/ssh:ro
      - ${ODOO_ROOT}/pycharm/.PyCharmCE2016.3:/root/.PyCharmCE2016.3
      - ${ODOO_ROOT}/pycharm/.PyCharm.java:/root/.java
      - ${ODOO_ROOT}/pycharm/projects:/root/PycharmProjects
      
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=STRONG_PG_SUPERUSER_PASSWORD
    image: postgres:11
    network_mode: "host"
    ports:
      - "5432:5432"
    user: ${UID}:${UID}
    volumes:
      - ${ODOO_ROOT}/postgres/data:/var/lib/postgresql/data
      - ${ODOO_ROOT}/postgres/init:/docker-entrypoint-initdb.d
      - /etc/passwd:/etc/passwd:ro

